package com.pilltrack.model.enums;

public enum NotificationType {
    MEDICATION_REMINDER,
    DOSE_LOGGED,
    LOW_STOCK,
    MEDICATION_UPDATED_BY_DOCTOR,
    MEDICATION_CHANGE_REQUEST,
    MEDICATION_CHANGE_APPROVED,
    MEDICATION_CHANGE_REJECTED,
    ORDER_PLACED,
    ORDER_CONFIRMED,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    ORDER_CANCELLED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILED,
    SHOP_VERIFIED,
    SHOP_REJECTED,
    NEW_ORDER,
    SYSTEM_ALERT,
    DOCTOR_ASSIGNED,
    APPOINTMENT_REQUESTED,
    APPOINTMENT_APPROVED,
    APPOINTMENT_REJECTED,
    APPOINTMENT_CANCELLED,
    APPOINTMENT_COMPLETED
}
